// <auto-generated />
using System;
using GameApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameApi.Data.Migrations
{
    [DbContext(typeof(GameApiDbContext))]
    [Migration("20260923120922_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameApi.Data.Entities.Game", b =>
                {
                    b.Property<long>("TableId")
                        .HasColumnType("bigint");

                    b.Property<string>("Format")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TournamentGroup")
                        .HasColumnType("text");

                    b.Property<long?>("TournamentId")
                        .HasColumnType("bigint");

                    b.Property<string>("TournamentName")
                        .HasColumnType("text");

                    b.Property<long?>("TournamentParentId")
                        .HasColumnType("bigint");

                    b.HasKey("TableId");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("TournamentParentId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameApi.Data.Entities.PlayerGame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BgaName")
                        .HasColumnType("text");

                    b.Property<string>("BgaUserId")
                        .HasColumnType("text");

                    b.Property<string>("Deck")
                        .HasColumnType("text");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean");

                    b.Property<string>("PlayedCards")
                        .HasColumnType("text");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TableId", "BgaUserId");

                    b.ToTable("PlayerGames");
                });

            modelBuilder.Entity("GameApi.Data.Entities.PlayerTournament", b =>
                {
                    b.Property<long>("TournamentParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("BgaUserId")
                        .HasColumnType("text");

                    b.Property<string>("AdminAdjustmentNote")
                        .HasColumnType("text");

                    b.Property<int>("AdminLossesAdjustment")
                        .HasColumnType("integer");

                    b.Property<int>("AdminWinsAdjustment")
                        .HasColumnType("integer");

                    b.Property<string>("BgaName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DecksPlayed")
                        .HasColumnType("integer");

                    b.Property<string>("Faction")
                        .HasColumnType("text");

                    b.Property<string>("Hero")
                        .HasColumnType("text");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("MainDeck")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("TournamentParentId", "BgaUserId");

                    b.ToTable("PlayerTournaments");
                });

            modelBuilder.Entity("GameApi.Data.Entities.SyncCursor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Since")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SyncCursors");
                });

            modelBuilder.Entity("GameApi.Data.Entities.Tournament", b =>
                {
                    b.Property<long>("TournamentParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalGames")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("TournamentParentName")
                        .HasColumnType("text");

                    b.HasKey("TournamentParentId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("GameApi.Data.Entities.PlayerGame", b =>
                {
                    b.HasOne("GameApi.Data.Entities.Game", "Game")
                        .WithMany("PlayerGames")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameApi.Data.Entities.Game", b =>
                {
                    b.Navigation("PlayerGames");
                });
#pragma warning restore 612, 618
        }
    }
}
